Repository artsy/lint-changed, pull requests merged in 2020-03, with the labels that each got.

#1 Setup npm publishing
  .autorc
  .circleci/config.yml
  bin/lint-changed.js
  package.json
  src/lint-changed.ts
  yarn.lock
Labels: Version: Major

#2 Fix typos in README
  README.md
Labels: Version: Trivial

#3 Fix error when trying to find files that changed on master
  src/lint-changed.ts
Labels: Version: Patch

#4 Refactor for legibility
  src/lint-changed.ts
Labels: Version: Patch

#5 Add artsy OSS banner
  README.md
Labels: Version: Trivial

#7 Add renovate config
  renovate.json
Labels: Version: Trivial

#11 Add a shout-out to `pull-lock`
  README.md
Labels: Version: Trivial, documentation

#12 Lint only files changed since branch off of master
  src/lint-changed.ts
Labels: Version: Patch

#13 Only lint existing files, limit concurrency
  package.json
  src/lint-changed.ts
  yarn.lock
Labels: Version: Patch
