Repository artsy/lint-changed, pull requests merged in 2021-07, with the labels that each got.

#46 Command line support
  README.md
  package-lock.json
  package.json
  src/lint-changed.ts
  yarn.lock
Labels: Version: Major

#47 fix: Remove package lock
  package-lock.json
Labels: Version: Patch

#48 fix: Add engines to lock
  package.json
Labels: Version: Minor
